import type {BetaReadinessManifest,BetaReadinessReport} from "./types";
export const RELEASE_CANDIDATE_MATERIAL_VERSION="investing-release-candidate-material/v1" as const;
export const RELEASE_CANDIDATE_VERSION="investing-release-candidate/v1" as const;
export const EFFECTIVE_READINESS_VERSION="investing-effective-beta-readiness/v1" as const;
export const READINESS_REVOCATION_VERSION="investing-effective-readiness-revocation/v1" as const;
export type ReleaseEnvironment="preview"|"staging"|"production";
export type ReleaseCandidateMaterial=Readonly<{contractVersion:typeof RELEASE_CANDIDATE_MATERIAL_VERSION;
 commitSha:string;lockfileHash:string;migrationsHash:string;buildId:string;buildArtifactHash:string;
 runtimeProfile:Readonly<{id:string;version:string}>;targetEnvironment:ReleaseEnvironment;
 operationalConfigHash:string;createdAt:string}>;
export type ReleaseCandidate=Readonly<{contractVersion:typeof RELEASE_CANDIDATE_VERSION;
 candidateId:string;candidateHash:string;material:ReleaseCandidateMaterial}>;
export type EffectiveReadiness=Readonly<{contractVersion:typeof EFFECTIVE_READINESS_VERSION;
 assessmentId:string;assessmentHash:string;candidateId:string;reportHash:string;
 targetEnvironment:ReleaseEnvironment;state:"effective_beta_ready"|"blocked";
 reason:null|"report_blocked"|"binding_mismatch"|"evidence_expired"|"prior_revoked";
 supersedesAssessmentId:string|null;evaluatedAt:string}>;
export type EffectiveReadinessRevocation=Readonly<{contractVersion:typeof READINESS_REVOCATION_VERSION;
 revocationId:string;revocationHash:string;assessmentId:string;candidateId:string;
 reason:"evidence_invalidated"|"build_invalidated"|"configuration_invalidated"|"operator_revoked";
 revokedAt:string;revokedBy:Readonly<{id:string;version:string}>}>;
export type EffectiveReadinessInput=Readonly<{candidate:ReleaseCandidate;
 manifest:BetaReadinessManifest;report:BetaReadinessReport;evaluatedAt:string;
 prior:EffectiveReadiness|null;priorRevocation:EffectiveReadinessRevocation|null}>;
export type ReleaseResult<T>=Readonly<{ok:true;value:T}>|Readonly<{ok:false;reason:string}>;
