module.exports = {
  apps: [
    {
      name: "syntrake-research-supervisor",
      script: "npm",
      args: "run research:supervisor",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 20,
      min_uptime: "30s",
      restart_delay: 5000,
      kill_timeout: 30000,
      time: true,
      env: {
        NODE_ENV: "production",
        RESEARCH_SUPABASE_SYNC: "1",
      },
      out_file: "artifacts/trading-research/runtime/pm2-supervisor.out.log",
      error_file: "artifacts/trading-research/runtime/pm2-supervisor.err.log",
      merge_logs: true,
    },
    {
      name: "syntrake-research-sync",
      script: "npm",
      args: "run research:sync:loop -- --intervalSeconds=60",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 20,
      min_uptime: "30s",
      restart_delay: 5000,
      kill_timeout: 15000,
      time: true,
      env: {
        NODE_ENV: "production",
        RESEARCH_SUPABASE_SYNC: "1",
      },
      out_file: "artifacts/trading-research/runtime/pm2-sync.out.log",
      error_file: "artifacts/trading-research/runtime/pm2-sync.err.log",
      merge_logs: true,
    },
    {
      name: "syntrake-research-data-backfill",
      script: "npm",
      args: "run research:data-backfill:loop -- --intervalMinutes=360",
      cwd: __dirname,
      interpreter: "none",
      autorestart: true,
      max_restarts: 20,
      min_uptime: "30s",
      restart_delay: 10000,
      kill_timeout: 30000,
      time: true,
      env: {
        NODE_ENV: "production",
        RESEARCH_SUPABASE_SYNC: "1",
      },
      out_file: "artifacts/trading-research/runtime/pm2-backfill.out.log",
      error_file: "artifacts/trading-research/runtime/pm2-backfill.err.log",
      merge_logs: true,
    },
  ],
};
