(() => {
"use strict";
window.fetch=()=>Promise.reject(new Error("UX-T1R isolation guard: network requests are disabled."));
const NAV=[["home","⌂","Home"],["portfolio","▣","Portfolio"],["plan","◇","Plan"]];
const STATES=new Set(["new_user_unclassified","no_portfolio_no_plan","plan_setup_in_progress","plan_ready_no_portfolio","paper_portfolio_active","data_incomplete","data_stale","latest_evaluation_no_engine_blocker","attention_required","engine_decision_recorded","unavailable"]);
const NO_ACCOUNT=new Set(["new_user_unclassified","no_portfolio_no_plan","plan_setup_in_progress","plan_ready_no_portfolio"]);
const JOURNEY=[
["Welcome","Welcome to Investing","Choose a starting point. Nothing you select here creates positions or moves money.","Get started"],
["Starting point","No portfolio yet","First, tell us what you want a future Paper portfolio to be designed around.","Choose an objective"],
["Objective","What are you investing for?","Selected input: long-term capital growth.","Continue"],
["Horizon","How long could the money stay invested?","Selected input: long horizon.","Continue"],
["Contribution intent","Would you plan to add money regularly?","Selected input: €500 per month. This is an intention, not a payment instruction.","Continue"],
["Risk comfort","How much movement would feel manageable?","Selected input: balanced comfort with changes in value.","Review selections"],
["Review","Review your selected inputs","Long-term growth · long horizon · €500 monthly intention · balanced risk comfort.","Prepare plan"],
["Plan ready","Your plan inputs are ready","No portfolio, positions or money have been created.","Create Paper portfolio"],
["First evaluation","Paper portfolio created","A simulation-only portfolio now exists. The first Paper evaluation is ready to view.","View first evaluation"]];
let currentView="home",currentState="attention_required",journeyStep=0,showRecorded=false,firstTransition=false,setupPaused=false;
const truth=(c,m)=>`<div data-truth="${c}">${m}</div>`;
const hasAccount=()=>!NO_ACCOUNT.has(currentState);
const freshness=()=>!hasAccount()?"":currentState==="data_stale"?truth("A",`<div class="freshness warn"><span class="status-dot"></span><span>Historical values · <strong>not current</strong></span></div>`):currentState==="unavailable"?truth("A",`<div class="freshness bad"><span class="status-dot"></span><span>Update unavailable · <strong>nothing changed</strong></span></div>`):currentState==="data_incomplete"?truth("A",`<div class="freshness bad"><span class="status-dot"></span><span>Missing prices · <strong>check incomplete</strong></span></div>`):truth("A",`<div class="freshness"><span class="status-dot"></span><span>Paper check · <strong>2 Aug 2026, 09:12 UTC</strong></span></div>`);
const header=(t,d,setup=false)=>`<div class="page-head"><div><div class="eyebrow">${setup?"Investing setup":"Investing · Paper"}</div><h1>${t}</h1><p>${d}</p></div>${freshness()}</div>`;
const paperBanner=()=>truth("A",`<div class="paper-banner"><b>Paper only.</b> These values and positions are simulations. No real money is connected.</div>`);
const technicalEvidence=()=>truth("A",`<details class="disclosure"><summary>Technical evidence</summary><div class="evidence-summary"><div><b>Data used</b><span>Paper positions, Paper cash and a recorded market snapshot.</span></div><div><b>Evaluation time</b><span>2 Aug 2026, 09:12 UTC</span></div><div><b>Scope</b><span>This Paper account and selected plan limits only.</span></div><div><b>Limitations</b><span>This does not establish overall portfolio health.</span></div></div><div class="technical-details"><b>Technical details</b><p>Account pa_8f21 · mandate snapshot ms_balanced_v3 · market snapshot ms_20260802_0912 · run run_paper_08f21 · evidence hash 9fb2…14ce · reason position_limit_exceeded · executable:false.</p></div></details>`);
const allocation=()=>truth("B",`<section class="panel"><div class="panel-head"><div><span class="kicker">Estimated allocation</span><h2>Paper positions</h2></div><span class="chip">Full price coverage</span></div><div class="allocation"><div class="donut"></div><div class="legend"><div class="legend-row"><i class="swatch" style="background:#63d6b5"></i><span>Global equity</span><b>46%</b></div><div class="legend-row"><i class="swatch" style="background:#7ba7ff"></i><span>Bonds</span><b>28%</b></div><div class="legend-row"><i class="swatch" style="background:#f2bf68"></i><span>Europe equity</span><b>14%</b></div><div class="legend-row"><i class="swatch" style="background:#46616a"></i><span>Paper cash</span><b>12%</b></div></div></div><p class="muted tiny section-gap">Based on simulated positions and prices available at the recorded check time.</p></section>`);
const journey=()=>{const s=JOURNEY[journeyStep];return `${header(s[1],s[2],true)}<section class="panel journey-card"><div class="journey-progress"><span>Step ${journeyStep+1} of ${JOURNEY.length}</span><i style="width:${(journeyStep+1)/JOURNEY.length*100}%"></i></div><span class="kicker">${s[0]}</span>${journeyStep===6?`<div class="review-inputs"><span>Objective <b>Long-term growth</b></span><span>Horizon <b>Long</b></span><span>Contribution intent <b>€500 / month</b></span><span>Risk comfort <b>Balanced</b></span></div>`:""}<div class="journey-actions">${journeyStep?`<button class="button secondary" data-journey-back>Back</button>`:""}<button class="button" data-journey-next>${s[3]}</button>${journeyStep<JOURNEY.length-1?`<button class="text-action journey-exit" data-journey-exit>Save and exit</button>`:""}</div><p class="tiny muted">Static interaction only. Selections are not saved and no real account, position or payment is created.</p></section>`};
const pausedSetup=()=>`${header("Your setup is paused","Your current step is kept in this browser view only. Nothing has been saved or created.",true)}<section class="panel compact-state"><span class="kicker">Setup progress</span><h2>Continue where you left off</h2><p>You paused at step ${journeyStep+1} of ${JOURNEY.length}. You can continue from the same step or return to the previous step after resuming.</p><button class="button" data-continue-setup>Continue setup</button><p class="tiny muted">No Paper account, position, payment or real evaluation was created.</p></section>`;
const noPortfolio=withPlan=>withPlan?`${header("Your plan inputs are ready","There is no portfolio yet and no evaluation has taken place.",true)}<section class="panel compact-state"><span class="kicker">Next step</span><h2>Create a Paper portfolio simulation</h2><p>Your selected inputs can create a simulated portfolio. No real position or money will be created.</p><button class="button" data-start-paper>Create Paper portfolio</button></section>`:journey();
const unavailable=()=>`${header("We could not update your Paper portfolio","The latest prices or evaluation result could not be loaded.")}${paperBanner()}${truth("A",`<section class="panel compact-state unavailable-card"><span class="state-icon small">!</span><span class="kicker">What this means</span><h2>No current conclusion is available</h2><p>Your simulated positions and selected plan inputs were not changed. Previously recorded conclusions are not shown as current.</p><button class="button">Try again</button></section>`)}`;
const incomplete=()=>`${header("Some prices are missing","The portfolio check could not be completed, so no current conclusion is shown.")}${paperBanner()}${truth("A",`<section class="panel priority-card"><span class="kicker">Next step</span><h2>Refresh the missing prices</h2><p>Two of six Paper positions did not have a usable price. Value, allocation and concentration may therefore be incomplete.</p><button class="button">Refresh data</button></section>`)}${technicalEvidence()}`;
const priority=noIssue=>truth("A",`<section class="panel priority-card ${noIssue?"calm":"attention"}"><span class="kicker">${noIssue?"Latest scoped check":"Your priority"}</span><h2>${noIssue?"No issue was found in the checks that ran":"One position is above your selected limit"}</h2><p>${noIssue?"The available Paper data passed the specific limits that were checked. This does not confirm overall portfolio health.":"VWCE is estimated at 18.4%, compared with the selected 15% position limit."}</p>${noIssue?"":`<a class="button" href="#portfolio" data-view-link="portfolio">Review concentration</a>`}</section>`);
const valueCard=()=>truth("B",`<section class="panel"><span class="kicker">Estimated Paper value</span><div class="metric">€84,260</div><p class="muted tiny">A recorded estimate based on simulated positions and available prices.</p><div class="impact section-gap"><span class="muted">Paper cash</span><strong>€10,114</strong></div></section>`);
const recordCard=()=>truth("A",`<section class="panel"><span class="kicker">About this check</span><h2>What was included</h2><div class="impact section-gap"><span class="muted">Price coverage</span><strong>Complete</strong></div><div class="impact"><span class="muted">Plan limits</span><strong>Selected inputs</strong></div>${technicalEvidence()}</section>`);
const recorded=noIssue=>`<div class="recorded-assessment ${currentState==="data_stale"&&!showRecorded?"is-hidden":""}">${currentState==="data_stale"?`<div class="recorded-label">Previously recorded assessment — not current</div>`:""}${priority(noIssue)}<div class="grid two section-gap">${valueCard()}${allocation()}</div><div class="section-gap">${recordCard()}</div></div>`;
const assessment=noIssue=>currentState==="data_stale"?`${header("Your Paper data is out of date","Values from the previous check are historical and must not be treated as current.")}${paperBanner()}${truth("A",`<section class="panel priority-card stale-priority"><span class="kicker">Your priority</span><h2>Refresh before reviewing the portfolio</h2><p>The prices used are 18 hours old. Refreshing only asks for newer data; it does not change positions or move money.</p><button class="button">Refresh data</button><button class="text-action" data-show-recorded>View recorded assessment</button></section>`)}${recorded(false)}`:`${header(noIssue?"No issue found in the checks that ran":"One position needs your attention",noIssue?"The result is limited to available Paper data and selected plan limits.":"Review the reason and a simulation-only next step.")}${paperBanner()}${recorded(noIssue)}`;
const concentration=()=>{if(!hasAccount())return noPortfolio(currentState==="plan_ready_no_portfolio");if(currentState==="unavailable")return unavailable();if(currentState==="data_incomplete")return incomplete();if(currentState==="latest_evaluation_no_engine_blocker")return assessment(true);const old=currentState==="data_stale";return `${header("Review concentration",old?"Previously recorded assessment — not current.":"A read-only explanation of the latest Paper check.")}${paperBanner()}${old?`<div class="recorded-label">Previously recorded assessment — not current</div>`:""}${truth("B",`<section class="panel narrative"><span class="kicker">Read-only review</span><h2>One simulated position is above the selected limit</h2><div class="narrative-steps"><div><b>What was detected</b><span>VWCE is estimated at 18.4% of the Paper portfolio.</span></div><div><b>Compared with the evaluated limit</b><span>The selected single-position limit used was 15%.</span></div><div><b>Why it matters</b><span>The estimate is 3.4 percentage points above that limit.</span></div><div><b>Estimated Paper impact</b><span>A simulated adjustment would estimate the position at 14.8%.</span></div><div><b>Next safe action</b><span>Inspect a Paper adjustment preview. Nothing will be placed.</span></div></div></section>`)}<div class="grid equal section-gap">${truth("A",`<section class="panel proposal"><span class="kicker">Simulation only</span><h2>Paper adjustment preview</h2><div class="impact section-gap"><span class="muted">Estimated notional</span><strong>€840</strong></div><div class="impact"><span class="muted">Estimated position after preview</span><strong>14.8%</strong></div><p class="safe-note">This creates a simulation only. No order will be placed.</p><button class="button">Create Paper adjustment preview</button></section>`)}${truth("A",`<section class="panel"><span class="kicker">What is known</span><h2>No Paper order is recorded</h2><p class="muted">This statement is limited to this proposal and recorded check time.</p>${technicalEvidence()}<a class="button secondary" href="#home" data-view-link="home">Back to Home</a></section>`)}</div>`};
const plan=()=>!hasAccount()?`${header("Your selected inputs","These choices describe a future Paper portfolio. They are not saved by this prototype.",true)}<div class="grid two">${truth("A",`<section class="panel"><span class="kicker">Selected preferences</span><h2>Long-term capital growth</h2><div class="impact section-gap"><span class="muted">Horizon</span><strong>Long</strong></div><div class="impact"><span class="muted">Risk comfort</span><strong>Balanced</strong></div><div class="impact"><span class="muted">Contribution intent</span><strong>€500 / month</strong></div></section>`)}<section class="panel"><span class="kicker">What happens next</span><h2>Review these inputs before creating a Paper portfolio</h2><p class="muted">No positions or money exist yet.</p><a class="button secondary" href="#home" data-view-link="home">Return to setup</a></section></div>`:`${header("Your selected plan inputs","These are the preferences used for the recorded Paper check.")}<div class="grid two">${truth("A",`<section class="panel"><span class="kicker">Selected preferences</span><h2>Long-term capital growth</h2><div class="impact section-gap"><span class="muted">Horizon</span><strong>Long</strong></div><div class="impact"><span class="muted">Risk comfort</span><strong>Balanced</strong></div><div class="impact"><span class="muted">Contribution intent</span><strong>€500 / month</strong></div></section>`)}${truth("A",`<section class="panel"><span class="kicker">Limit used for this check</span><h2>15% per position</h2><p class="muted">This page shows the selected inputs used by the recorded Paper check. Editing is not available in this static prototype.</p>${technicalEvidence()}</section>`)}</div>`;
function home(){if(setupPaused)return pausedSetup();if(firstTransition)return journey();if(currentState==="new_user_unclassified"||currentState==="no_portfolio_no_plan")return noPortfolio(false);if(currentState==="plan_setup_in_progress"){journeyStep=Math.max(2,Math.min(journeyStep,6));return journey()}if(currentState==="plan_ready_no_portfolio")return noPortfolio(true);if(currentState==="data_incomplete")return incomplete();if(currentState==="unavailable")return unavailable();if(currentState==="latest_evaluation_no_engine_blocker")return assessment(true);return assessment(false)}
function renderNav(){const m=NAV.map(([k,i,l])=>`<a class="nav-link ${currentView===k?"active":""}" href="#${k}" data-view-link="${k}"><span class="nav-icon">${i}</span><span>${l}</span></a>`).join("");document.querySelector(".main-nav").innerHTML=m;document.querySelector(".mobile-nav").innerHTML=m;document.body.classList.toggle("no-paper-account",!hasAccount())}
function bind(){document.querySelectorAll("[data-view-link]").forEach(l=>l.addEventListener("click",e=>{e.preventDefault();currentView=l.dataset.viewLink;location.hash=currentView;render();scrollTo(0,0)}));document.querySelectorAll("[data-journey-next]").forEach(b=>b.addEventListener("click",()=>{if(journeyStep<JOURNEY.length-1){journeyStep++;render()}else{firstTransition=false;setupPaused=false;currentState="paper_portfolio_active";currentView="home";document.getElementById("state-switcher").value=currentState;render()}scrollTo(0,0)}));document.querySelectorAll("[data-journey-back]").forEach(b=>b.addEventListener("click",()=>{journeyStep=Math.max(0,journeyStep-1);render();scrollTo(0,0)}));document.querySelectorAll("[data-journey-exit]").forEach(b=>b.addEventListener("click",()=>{setupPaused=true;firstTransition=false;currentState="plan_setup_in_progress";currentView="home";location.hash="home";document.getElementById("state-switcher").value=currentState;render();scrollTo(0,0)}));document.querySelectorAll("[data-continue-setup]").forEach(b=>b.addEventListener("click",()=>{setupPaused=false;firstTransition=true;render();scrollTo(0,0)}));document.querySelectorAll("[data-start-paper]").forEach(b=>b.addEventListener("click",()=>{journeyStep=8;firstTransition=true;setupPaused=false;currentState="paper_portfolio_active";document.getElementById("state-switcher").value=currentState;render()}));document.querySelectorAll("[data-show-recorded]").forEach(b=>b.addEventListener("click",()=>{showRecorded=true;render()}))}
function render(){renderNav();document.getElementById("page").innerHTML=({home,portfolio:concentration,plan})[currentView]();document.title=`${NAV.find(([k])=>k===currentView)[2]} · Syntrake UX-T1R`;bind()}
document.getElementById("state-switcher").addEventListener("change",e=>{if(STATES.has(e.target.value)){currentState=e.target.value;showRecorded=false;firstTransition=false;setupPaused=false;if(currentState==="new_user_unclassified")journeyStep=0;if(currentState==="no_portfolio_no_plan")journeyStep=1;render()}});
const hash=location.hash.slice(1);if(NAV.some(([k])=>k===hash))currentView=hash;addEventListener("hashchange",()=>{const n=location.hash.slice(1);if(NAV.some(([k])=>k===n)){currentView=n;render()}});render();
})();
