export const SHADOW_PARITY_SNAPSHOT_VERSION = "investing-shadow-parity-snapshot/v1" as const;
export const SHADOW_PARITY_CYCLE_VERSION = "investing-shadow-parity-cycle/v1" as const;
export const SHADOW_PARITY_POLICY_VERSION = "investing-shadow-parity-policy/v1" as const;
export const SHADOW_PARITY_DIMENSIONS = ["identity", "cash", "positions", "pending_state", "valuation"] as const;
export type ShadowParityDimension = (typeof SHADOW_PARITY_DIMENSIONS)[number];
export type ShadowParityDimensionState = "passed" | "blocked" | "unavailable";
export type ShadowParityScope = Readonly<{tenantId:string;ownerId:string;portfolioId:string;accountId:string;authenticatedUserId:string}>;
export type ShadowParityPosition = Readonly<{symbol:string;quantity:number;valueEur:number|null}>;
export type ShadowParityPending = Readonly<{symbol:string;side:"buy"|"sell";quantity:number}>;
export type ShadowParitySnapshot = Readonly<{contractVersion:typeof SHADOW_PARITY_SNAPSHOT_VERSION;source:"legacy"|"canonical";
 sourceVersion:string;scope:ShadowParityScope;observedAt:string;cashEur:number|null;positions:readonly ShadowParityPosition[];
 pending:readonly ShadowParityPending[];valuationEur:number|null}>;
export type ShadowParityDimensionResult = Readonly<{dimension:ShadowParityDimension;state:ShadowParityDimensionState;
 reason:null|"source_unavailable"|"identity_mismatch"|"value_mismatch";differenceCount:number}>;
export type ShadowParityCycle = Readonly<{contractVersion:typeof SHADOW_PARITY_CYCLE_VERSION;cycleId:string;cycleHash:string;
 policyVersion:typeof SHADOW_PARITY_POLICY_VERSION;scope:ShadowParityScope;dayKey:string;observedAt:string;
 legacySnapshotHash:string;canonicalSnapshotHash:string;state:ShadowParityDimensionState;
 dimensions:readonly ShadowParityDimensionResult[]}>;
export type ShadowParityProgress = Readonly<{requiredCycles:30;consecutivePassedCycles:number;readyForCutover:boolean;
 latest:ShadowParityCycle|null;history:readonly ShadowParityCycle[]}>;
