import type {Metadata} from "next";import {createProductionReleaseReadinessOpsServiceV1} from
 "@/lib/investing/research/readiness/releaseOpsComposition.server";
export const metadata:Metadata={title:"Beta Readiness Ops | Syntrake"};export const runtime="nodejs";export const dynamic="force-dynamic";
const label=(v:string|null)=>v?.replaceAll("_"," ")??"—";const tone=(state:string)=>state==="effective_beta_ready"?
 "border-emerald-300/30 bg-emerald-400/10 text-emerald-100":"border-amber-300/30 bg-amber-400/10 text-amber-100";
export default async function ReleaseReadinessPage(){let result;try{result=await createProductionReleaseReadinessOpsServiceV1().load()}
 catch{result={ok:false as const,reason:"release_readiness_ops_read_failed"}}if(!result.ok)return <main className="min-h-screen bg-slate-950 p-8 text-white"><section className="mx-auto max-w-3xl rounded-3xl border border-red-300/20 bg-red-500/10 p-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-red-200">Beta readiness</p><h1 className="mt-3 text-3xl font-bold">Read-only status unavailable</h1><p className="mt-3 text-slate-300">The authenticated OPS projection could not be loaded.</p></section></main>;
 const snapshot=result.value;return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#15334a,#020617_50%)] p-5 text-white md:p-10"><div className="mx-auto max-w-7xl"><header className="rounded-[32px] border border-white/10 bg-slate-950/60 p-7"><p className="text-xs font-bold uppercase tracking-[.3em] text-cyan-200">Phase 7 · Beta gate</p><h1 className="mt-3 text-4xl font-black">Release readiness, read only</h1><p className="mt-3 max-w-3xl text-slate-300">Effective state, release binding, supersession and revocation history. This surface cannot activate beta or modify evidence.</p><p className="mt-4 text-xs text-slate-500">Snapshot {new Date(snapshot.generatedAt).toLocaleString("pt-PT")}</p></header>
 {snapshot.current?<section className={`mt-6 rounded-[28px] border p-6 ${tone(snapshot.current.state)}`}><p className="text-xs font-bold uppercase tracking-wider">Effective release candidate</p><h2 className="mt-2 text-3xl font-black">{label(snapshot.current.state)}</h2><div className="mt-5 grid gap-3 text-sm md:grid-cols-3"><p><b>Environment</b><br/>{snapshot.current.environment}</p><p><b>Build</b><br/>{snapshot.current.buildId}</p><p><b>Commit</b><br/><span className="font-mono text-xs">{snapshot.current.commitSha}</span></p><p><b>Reason</b><br/>{label(snapshot.current.revocationReason??snapshot.current.reason)}</p><p><b>Evaluated</b><br/>{new Date(snapshot.current.evaluatedAt).toLocaleString("pt-PT")}</p><p><b>Candidate</b><br/><span className="font-mono text-xs">{snapshot.current.candidateId}</span></p></div></section>:<section className="mt-6 rounded-[28px] border border-white/10 bg-white/[.04] p-6 text-slate-300">No effective readiness assessment has been recorded.</section>}
 <section className="mt-6 rounded-[28px] border border-white/10 bg-slate-950/55 p-6"><h2 className="text-2xl font-bold">Immutable history</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="py-3">Environment</th><th>Build / commit</th><th>Effective state</th><th>Reason</th><th>Evaluated</th><th>Supersedes</th></tr></thead><tbody>{snapshot.history.map(row=><tr key={row.assessmentId} className="border-t border-white/5"><td className="py-3">{row.environment}</td><td><div>{row.buildId}</div><div className="font-mono text-xs text-slate-500">{row.commitSha.slice(0,12)}</div></td><td>{label(row.state)}</td><td>{label(row.revocationReason??row.reason)}</td><td>{new Date(row.evaluatedAt).toLocaleString("pt-PT")}</td><td className="max-w-44 truncate font-mono text-xs text-slate-500">{row.supersedesAssessmentId??"—"}</td></tr>)}</tbody></table></div></section>
 <p className="mt-5 text-xs text-slate-500">Read only · no canonical payload · no activation controls</p></div></main>}
