import {
  assertHashRefDomainV1,
  assertHashDomainAdmittedForHashingV1,
  hashRefV1,
  i5ResearchInternalCanonicalJsonBytesV1,
  sha256HexV1,
  type CanonicalJsonValue,
  type CanonicalSha256HexV1,
  type HashRefV1,
} from "./canonical";

export const robustnessComparisonPolicyV1 = Object.freeze({ policyId:"ROBUSTNESS_COMPARISON_POLICY_V20260927" as const, metricRegistryVersion:"METRIC_REGISTRY_V20260927" as const, minimumCompleteFolds:3, minimumNeighborhoodMembers:3, minimumTradeCount:20, minimumRebalanceCount:5 });
export type DirectionalComparisonMetricIdV1="TOTAL_RETURN"|"CAGR"|"SHARPE_RATIO"|"SORTINO_RATIO"|"CALMAR_RATIO"|"BENCHMARK_RELATIVE_RETURN"|"MAX_DRAWDOWN"|"MAX_DRAWDOWN_DURATION"|"MAX_DRAWDOWN_RECOVERY"|"TURNOVER";
export type ComparisonMetricIdV1=DirectionalComparisonMetricIdV1|"TRADE_COUNT"|"REBALANCE_COUNT"|"AVERAGE_GROSS_EXPOSURE";
export type ExperimentComparisonProtocolV1=Readonly<{schemaVersion:"EXPERIMENT_COMPARISON_PROTOCOL_V1";policyId:"ROBUSTNESS_COMPARISON_POLICY_V20260927";referenceExperiment:HashRefV1;subjectExperiment:HashRefV1;referenceExperimentParameters:HashRefV1;subjectExperimentParameters:HashRefV1;referenceResult:HashRefV1;subjectResult:HashRefV1;referenceValidationResult:HashRefV1;subjectValidationResult:HashRefV1;metricRegistryVersion:"METRIC_REGISTRY_V20260927";primaryMetricId:DirectionalComparisonMetricIdV1;comparisonMetricIds:readonly ComparisonMetricIdV1[];neighborhoodExperimentRefs:readonly HashRefV1[]}>;
const protocolKeys=new Set(["schemaVersion","policyId","referenceExperiment","subjectExperiment","referenceExperimentParameters","subjectExperimentParameters","referenceResult","subjectResult","referenceValidationResult","subjectValidationResult","metricRegistryVersion","primaryMetricId","comparisonMetricIds","neighborhoodExperimentRefs"]);
const higher=new Set<DirectionalComparisonMetricIdV1>(["TOTAL_RETURN","CAGR","SHARPE_RATIO","SORTINO_RATIO","CALMAR_RATIO","BENCHMARK_RELATIVE_RETURN"]);const lower=new Set<DirectionalComparisonMetricIdV1>(["MAX_DRAWDOWN","MAX_DRAWDOWN_DURATION","MAX_DRAWDOWN_RECOVERY","TURNOVER"]);const descriptive=new Set<ComparisonMetricIdV1>(["TRADE_COUNT","REBALANCE_COUNT","AVERAGE_GROSS_EXPOSURE"]);
export function metricDirectionV1(metricId:ComparisonMetricIdV1):"HIGHER_IS_BETTER"|"LOWER_IS_BETTER"|"DESCRIPTIVE_ONLY"{if(higher.has(metricId as DirectionalComparisonMetricIdV1))return"HIGHER_IS_BETTER";if(lower.has(metricId as DirectionalComparisonMetricIdV1))return"LOWER_IS_BETTER";if(descriptive.has(metricId))return"DESCRIPTIVE_ONLY";throw new Error("UNSUPPORTED_COMPARISON_METRIC");}
export function canonicalExperimentComparisonProtocolV1(input:ExperimentComparisonProtocolV1):CanonicalJsonValue{assertClosedPlainObject(input,protocolKeys,"ExperimentComparisonProtocol");if(input.schemaVersion!=="EXPERIMENT_COMPARISON_PROTOCOL_V1")throw new Error("COMPARISON_PROTOCOL_SCHEMA_INVALID");if(input.policyId!==robustnessComparisonPolicyV1.policyId)throw new Error("COMPARISON_POLICY_INVALID");if(input.metricRegistryVersion!==robustnessComparisonPolicyV1.metricRegistryVersion)throw new Error("COMPARISON_METRIC_REGISTRY_INVALID");const referenceExperiment=checkedRef(input.referenceExperiment,"SYNTRAKE:EXPERIMENT:V1");const subjectExperiment=checkedRef(input.subjectExperiment,"SYNTRAKE:EXPERIMENT:V1");if(referenceExperiment.hashHex===subjectExperiment.hashHex)throw new Error("COMPARISON_SUBJECT_EQUALS_REFERENCE");const referenceExperimentParameters=checkedRef(input.referenceExperimentParameters,"SYNTRAKE:EXPERIMENT_PARAMETERS:V1");const subjectExperimentParameters=checkedRef(input.subjectExperimentParameters,"SYNTRAKE:EXPERIMENT_PARAMETERS:V1");const referenceResult=checkedRef(input.referenceResult,"SYNTRAKE:RESULT:V1");const subjectResult=checkedRef(input.subjectResult,"SYNTRAKE:RESULT:V1");const referenceValidationResult=checkedRef(input.referenceValidationResult,"SYNTRAKE:VALIDATION_RESULT:V1");const subjectValidationResult=checkedRef(input.subjectValidationResult,"SYNTRAKE:VALIDATION_RESULT:V1");if(metricDirectionV1(input.primaryMetricId)==="DESCRIPTIVE_ONLY")throw new Error("PRIMARY_METRIC_NOT_DIRECTIONAL");const comparisonMetricIds=canonicalMetricIds(input.comparisonMetricIds);if(!comparisonMetricIds.includes(input.primaryMetricId))throw new Error("PRIMARY_METRIC_NOT_REQUESTED");const neighborhoodExperimentRefs=canonicalExperimentRefs(input.neighborhoodExperimentRefs);if(!neighborhoodExperimentRefs.some(ref=>ref.hashHex===subjectExperiment.hashHex))throw new Error("NEIGHBORHOOD_MISSING_SUBJECT");return{schemaVersion:input.schemaVersion,policyId:input.policyId,referenceExperiment,subjectExperiment,referenceExperimentParameters,subjectExperimentParameters,referenceResult,subjectResult,referenceValidationResult,subjectValidationResult,metricRegistryVersion:input.metricRegistryVersion,primaryMetricId:input.primaryMetricId,comparisonMetricIds,neighborhoodExperimentRefs};}
export function canonicalExperimentComparisonProtocolBytesV1(input:ExperimentComparisonProtocolV1):Buffer{return i5ResearchInternalCanonicalJsonBytesV1(canonicalExperimentComparisonProtocolV1(input));}
export function hashExperimentComparisonProtocolV1(input:ExperimentComparisonProtocolV1):CanonicalSha256HexV1{assertHashDomainAdmittedForHashingV1("SYNTRAKE:EXPERIMENT_COMPARISON_PROTOCOL:V1");const payload=canonicalExperimentComparisonProtocolV1(input);return sha256HexV1(Buffer.concat([Buffer.from("SYNTRAKE:EXPERIMENT_COMPARISON_PROTOCOL:V1\n","utf8"),i5ResearchInternalCanonicalJsonBytesV1(payload)]));}
function checkedRef(ref:HashRefV1,domain:Parameters<typeof assertHashRefDomainV1>[1]):HashRefV1{const canonical=hashRefV1(ref);assertHashRefDomainV1(canonical,domain);return canonical;}
function canonicalMetricIds(input:readonly ComparisonMetricIdV1[]):readonly ComparisonMetricIdV1[]{if(!Array.isArray(input)||input.length===0)throw new Error("COMPARISON_METRICS_EMPTY");const copy=[...input];for(const metric of copy)metricDirectionV1(metric);copy.sort(byteCompare);if(new Set(copy).size!==copy.length)throw new Error("COMPARISON_METRICS_DUPLICATE");return Object.freeze(copy);}
function canonicalExperimentRefs(input:readonly HashRefV1[]):readonly HashRefV1[]{if(!Array.isArray(input)||input.length===0)throw new Error("NEIGHBORHOOD_EMPTY");const refs=input.map(ref=>checkedRef(ref,"SYNTRAKE:EXPERIMENT:V1"));refs.sort((a,b)=>byteCompare(a.hashHex,b.hashHex));for(let i=1;i<refs.length;i+=1)if(refs[i-1]!.hashHex===refs[i]!.hashHex)throw new Error("NEIGHBORHOOD_DUPLICATE");return Object.freeze(refs);}
function byteCompare(a:string,b:string):number{return Buffer.from(a,"utf8").compare(Buffer.from(b,"utf8"));}
function assertClosedPlainObject(value:unknown,allowed:ReadonlySet<string>,label:string):void{if(value===null||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error(label+" must be a plain object");const record=value as Record<string,unknown>;for(const key of Object.keys(record)){if(!allowed.has(key))throw new Error(label+" contains unknown key: "+key);if(record[key]===undefined)throw new Error(label+" contains undefined: "+key);}for(const key of allowed)if(!Object.hasOwn(record,key))throw new Error(label+" missing key: "+key);}
