begin;

do $$
begin
  if current_user <> 'postgres' then raise exception 'RL-8C1 prestate violation: migration executor must be postgres'; end if;
  if to_regnamespace('investing') is null or to_regnamespace('extensions') is null then raise exception 'RL-8C1 prestate violation: required schemas are missing'; end if;
  if to_regclass('investing.tenant_memberships') is null or to_regclass('investing.research_investigations') is null or to_regclass('investing.research_experiments') is null or to_regclass('investing.run_inputs_scientific_identities') is null or to_regclass('investing.research_results_scientific_identities') is null or to_regclass('investing.research_evidence_objects_scientific_identities') is null or to_regclass('investing.research_validation_protocols_scientific_identities') is null or to_regclass('investing.research_validation_results_scientific_identities') is null or to_regclass('investing.research_validation_assessment_protocols_scientific_identities') is null or to_regclass('investing.research_validation_assessment_results_scientific_identities') is null or to_regclass('investing.research_experiment_comparison_protocols_scientific_identities') is null or to_regclass('investing.research_experiment_comparison_results_scientific_identities') is null then raise exception 'RL-8C1 prestate violation: accepted post-Genesis predecessor surface is incomplete'; end if;
end $$;

do $$
declare v_role record;
begin
  select * into v_role from pg_catalog.pg_roles where rolname = 'investing_rl8_writer';
  if not found then
    create role investing_rl8_writer nologin noinherit nosuperuser nocreatedb nocreaterole noreplication nobypassrls;
  elsif v_role.rolcanlogin or v_role.rolinherit or v_role.rolsuper or v_role.rolcreatedb or v_role.rolcreaterole or v_role.rolreplication or v_role.rolbypassrls then
    raise exception 'RL-8C1 prestate violation: investing_rl8_writer exists with incompatible attributes';
  end if;
  if pg_catalog.pg_has_role('investing_app', 'investing_rl8_writer', 'member') then raise exception 'RL-8C1 prestate violation: investing_app must not be a member of investing_rl8_writer'; end if;
  if pg_catalog.pg_has_role('service_role', 'investing_rl8_writer', 'member') then raise exception 'RL-8C1 prestate violation: service_role must not be a member of investing_rl8_writer'; end if;
  if pg_catalog.pg_has_role('investing_rl8_writer', 'investing_owner', 'member') then raise exception 'RL-8C1 prestate violation: investing_rl8_writer must not inherit investing_owner'; end if;
end $$;

set local role investing_owner;

create unique index research_investigations_rl8c_authority_tuple_key on investing.research_investigations (research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context);
create unique index research_experiments_rl8c_subject_authority_hash_key on investing.research_experiments (research_experiment_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, experiment_hash_hex, experiment_parameters_hash_hex, research_ir_hash_hex);
create unique index run_inputs_rl8c_authority_hash_key on investing.run_inputs_scientific_identities (run_input_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_results_rl8c_run_input_hash_key on investing.research_results_scientific_identities (result_identity_id, run_input_identity_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_evidence_objects_rl8c_authority_hash_key on investing.research_evidence_objects_scientific_identities (evidence_identity_id, run_input_identity_id, result_identity_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_validation_protocols_rl8c_authority_hash_key on investing.research_validation_protocols_scientific_identities (research_validation_protocol_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_validation_results_rl8c_authority_hash_key on investing.research_validation_results_scientific_identities (research_validation_result_identity_id, research_validation_protocol_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_validation_assessment_protocols_rl8c_authority_hash_key on investing.research_validation_assessment_protocols_scientific_identities (research_validation_assessment_protocol_identity_id, research_investigation_id, research_validation_protocol_identity_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_validation_assessment_results_rl8c_authority_hash_key on investing.research_validation_assessment_results_scientific_identities (research_validation_assessment_result_identity_id, research_validation_assessment_protocol_identity_id, research_validation_result_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_experiment_comparison_protocols_rl8c_authority_hash_key on investing.research_experiment_comparison_protocols_scientific_identities (research_experiment_comparison_protocol_identity_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);
create unique index research_experiment_comparison_results_rl8c_authority_hash_key on investing.research_experiment_comparison_results_scientific_identities (research_experiment_comparison_result_identity_id, research_experiment_comparison_protocol_identity_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex);

create or replace function investing.rl8c_jsonb_has_number_v1(p_value jsonb) returns boolean language sql immutable strict set search_path = pg_catalog as $$
  select case jsonb_typeof(p_value) when 'number' then true when 'array' then exists (select 1 from pg_catalog.jsonb_array_elements(p_value) as e(value) where investing.rl8c_jsonb_has_number_v1(e.value)) when 'object' then exists (select 1 from pg_catalog.jsonb_each(p_value) as e(key, value) where investing.rl8c_jsonb_has_number_v1(e.value)) else false end
$$;

create or replace function investing.rl8c_canonical_jsonb_v1(p_value jsonb) returns text language plpgsql immutable strict set search_path = pg_catalog as $$
declare v_type text; v_out text;
begin
  v_type := pg_catalog.jsonb_typeof(p_value);
  if v_type = 'null' then return 'null'; elsif v_type = 'boolean' then return lower(p_value::text); elsif v_type = 'number' then raise exception 'RL-8C canonical JSON forbids numbers'; elsif v_type = 'string' then return pg_catalog.to_jsonb(p_value #>> '{}')::text; elsif v_type = 'array' then select '[' || coalesce(pg_catalog.string_agg(investing.rl8c_canonical_jsonb_v1(e.value), ',' order by e.ordinality), '') || ']' into v_out from pg_catalog.jsonb_array_elements(p_value) with ordinality as e(value, ordinality); return v_out; elsif v_type = 'object' then select '{' || coalesce(pg_catalog.string_agg(pg_catalog.to_jsonb(e.key)::text || ':' || investing.rl8c_canonical_jsonb_v1(e.value), ',' order by e.key collate "C"), '') || '}' into v_out from pg_catalog.jsonb_each(p_value) as e(key, value); return v_out; end if;
  raise exception 'RL-8C canonical JSON unsupported jsonb type: %', v_type;
end;
$$;

create or replace function investing.rl8c_sha256_hex_v1(p_hash_domain text, p_canonical_payload jsonb) returns text language sql immutable strict set search_path = pg_catalog, extensions as $$
  select upper(pg_catalog.encode(extensions.digest(pg_catalog.convert_to(p_hash_domain || E'\n' || investing.rl8c_canonical_jsonb_v1(p_canonical_payload), 'UTF8'), 'sha256'), 'hex'))
$$;

create or replace function investing.reject_research_scientific_promotion_update_delete_v1() returns trigger language plpgsql security invoker set search_path = pg_catalog as $$
begin raise exception 'research scientific promotion identities are append-only'; end;
$$;

revoke all on function investing.rl8c_jsonb_has_number_v1(jsonb) from public, anon, authenticated, service_role;
revoke all on function investing.rl8c_canonical_jsonb_v1(jsonb) from public, anon, authenticated, service_role;
revoke all on function investing.rl8c_sha256_hex_v1(text, jsonb) from public, anon, authenticated, service_role;
revoke all on function investing.reject_research_scientific_promotion_update_delete_v1() from public, anon, authenticated, service_role;

create table investing.research_scientific_promotion_protocols_scientific_identities (
  research_scientific_promotion_protocol_identity_id uuid primary key default gen_random_uuid(),
  operation text not null check (operation = 'RESEARCH_SCIENTIFIC_PROMOTION_PROTOCOL_CREATE_V1'),
  capability text not null check (capability = 'RESEARCH_MUTATE'),
  operation_scope text not null check (operation_scope = 'TENANT_SCOPE'),
  source_context text not null check (source_context = 'PURE_RESEARCH'),
  hash_algorithm text not null check (hash_algorithm = 'SHA-256'),
  hash_domain text not null check (hash_domain = 'SYNTRAKE:SCIENTIFIC_PROMOTION_PROTOCOL:V1'),
  hash_version text not null check (hash_version = 'SYNTRAKE_SHA256_V1'),
  hash_hex text not null check (hash_hex ~ '^[0-9A-F]{64}$'),
  canonical_payload jsonb not null,
  created_at timestamptz not null default transaction_timestamp(),
  constraint research_scientific_promotion_protocols_payload_check check (jsonb_typeof(canonical_payload) = 'object' and not investing.rl8c_jsonb_has_number_v1(canonical_payload) and canonical_payload->>'schemaVersion' = 'SCIENTIFIC_PROMOTION_PROTOCOL_V1' and investing.rl8c_sha256_hex_v1(hash_domain, canonical_payload) = hash_hex),
  constraint research_scientific_promotion_protocols_hash_key unique (hash_algorithm, hash_domain, hash_version, hash_hex),
  constraint research_scientific_promotion_protocols_rl8c_identity_hash_key unique (research_scientific_promotion_protocol_identity_id, hash_hex)
);

create unique index research_scientific_promotion_protocols_protocol_id_key on investing.research_scientific_promotion_protocols_scientific_identities ((canonical_payload->>'protocolId')) where hash_domain = 'SYNTRAKE:SCIENTIFIC_PROMOTION_PROTOCOL:V1';

create table investing.research_scientific_promotion_transitions_scientific_identities (
  research_scientific_promotion_transition_identity_id uuid primary key default gen_random_uuid(),
  operation text not null check (operation in ('RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1')),
  capability text not null check (capability = 'RESEARCH_MUTATE'), operation_scope text not null check (operation_scope = 'TENANT_SCOPE'), source_context text not null check (source_context = 'PURE_RESEARCH'),
  tenant_id uuid not null, principal_id uuid not null, tenant_membership_id uuid not null, research_investigation_id uuid not null, research_experiment_id uuid not null,
  research_scientific_promotion_protocol_identity_id uuid not null, protocol_hash_hex text not null check (protocol_hash_hex ~ '^[0-9A-F]{64}$'),
  subject_experiment_hash_hex text not null check (subject_experiment_hash_hex ~ '^[0-9A-F]{64}$'), subject_experiment_parameters_hash_hex text not null check (subject_experiment_parameters_hash_hex ~ '^[0-9A-F]{64}$'), subject_research_ir_hash_hex text not null check (subject_research_ir_hash_hex ~ '^[0-9A-F]{64}$'),
  predecessor_transition_identity_id uuid, predecessor_transition_hash_hex text check (predecessor_transition_hash_hex is null or predecessor_transition_hash_hex ~ '^[0-9A-F]{64}$'), predecessor_state text not null, resulting_state text not null,
  transition_hash_algorithm text not null check (transition_hash_algorithm = 'SHA-256'), transition_hash_domain text not null check (transition_hash_domain = 'SYNTRAKE:SCIENTIFIC_PROMOTION_TRANSITION:V1'), transition_hash_version text not null check (transition_hash_version = 'SYNTRAKE_SHA256_V1'), transition_hash_hex text not null check (transition_hash_hex ~ '^[0-9A-F]{64}$'),
  supersedes_transition_identity_id uuid, supersedes_transition_hash_hex text check (supersedes_transition_hash_hex is null or supersedes_transition_hash_hex ~ '^[0-9A-F]{64}$'), rejected_transition_identity_id uuid, rejected_transition_hash_hex text check (rejected_transition_hash_hex is null or rejected_transition_hash_hex ~ '^[0-9A-F]{64}$'),
  superseded_by_successor_protocol_identity_id uuid, superseded_by_successor_protocol_hash_hex text check (superseded_by_successor_protocol_hash_hex is null or superseded_by_successor_protocol_hash_hex ~ '^[0-9A-F]{64}$'), superseded_by_successor_root_transition_identity_id uuid, superseded_by_successor_root_transition_hash_hex text check (superseded_by_successor_root_transition_hash_hex is null or superseded_by_successor_root_transition_hash_hex ~ '^[0-9A-F]{64}$'),
  run_input_identity_id uuid, run_input_hash_hex text check (run_input_hash_hex is null or run_input_hash_hex ~ '^[0-9A-F]{64}$'), result_identity_id uuid, result_hash_hex text check (result_hash_hex is null or result_hash_hex ~ '^[0-9A-F]{64}$'), evidence_object_identity_id uuid, evidence_object_hash_hex text check (evidence_object_hash_hex is null or evidence_object_hash_hex ~ '^[0-9A-F]{64}$'),
  validation_protocol_identity_id uuid, validation_protocol_hash_hex text check (validation_protocol_hash_hex is null or validation_protocol_hash_hex ~ '^[0-9A-F]{64}$'), validation_result_identity_id uuid, validation_result_hash_hex text check (validation_result_hash_hex is null or validation_result_hash_hex ~ '^[0-9A-F]{64}$'),
  validation_assessment_protocol_identity_id uuid, validation_assessment_protocol_hash_hex text check (validation_assessment_protocol_hash_hex is null or validation_assessment_protocol_hash_hex ~ '^[0-9A-F]{64}$'), validation_assessment_result_identity_id uuid, validation_assessment_result_hash_hex text check (validation_assessment_result_hash_hex is null or validation_assessment_result_hash_hex ~ '^[0-9A-F]{64}$'),
  robustness_comparison_protocol_identity_id uuid, robustness_comparison_protocol_hash_hex text check (robustness_comparison_protocol_hash_hex is null or robustness_comparison_protocol_hash_hex ~ '^[0-9A-F]{64}$'), robustness_comparison_result_identity_id uuid, robustness_comparison_result_hash_hex text check (robustness_comparison_result_hash_hex is null or robustness_comparison_result_hash_hex ~ '^[0-9A-F]{64}$'),
  canonical_payload jsonb not null, created_at timestamptz not null default transaction_timestamp(),
  constraint research_scientific_promotion_transitions_membership_fk foreign key (tenant_membership_id, tenant_id, principal_id) references investing.tenant_memberships (tenant_membership_id, tenant_id, principal_id),
  constraint research_scientific_promotion_transitions_investigation_fk foreign key (research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context) references investing.research_investigations (research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context),
  constraint research_scientific_promotion_transitions_subject_experiment_fk foreign key (research_experiment_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex) references investing.research_experiments (research_experiment_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, experiment_hash_hex, experiment_parameters_hash_hex, research_ir_hash_hex),
  constraint research_scientific_promotion_transitions_protocol_fk foreign key (research_scientific_promotion_protocol_identity_id, protocol_hash_hex) references investing.research_scientific_promotion_protocols_scientific_identities (research_scientific_promotion_protocol_identity_id, hash_hex),
  constraint research_scientific_promotion_transitions_run_input_fk foreign key (run_input_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, run_input_hash_hex) references investing.run_inputs_scientific_identities (run_input_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_result_fk foreign key (result_identity_id, run_input_identity_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, result_hash_hex) references investing.research_results_scientific_identities (result_identity_id, run_input_identity_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_evidence_object_fk foreign key (evidence_object_identity_id, run_input_identity_id, result_identity_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, evidence_object_hash_hex) references investing.research_evidence_objects_scientific_identities (evidence_identity_id, run_input_identity_id, result_identity_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_validation_protocol_fk foreign key (validation_protocol_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, validation_protocol_hash_hex) references investing.research_validation_protocols_scientific_identities (research_validation_protocol_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_validation_result_fk foreign key (validation_result_identity_id, validation_protocol_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, validation_result_hash_hex) references investing.research_validation_results_scientific_identities (research_validation_result_identity_id, research_validation_protocol_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_validation_assessment_protocol_fk foreign key (validation_assessment_protocol_identity_id, research_investigation_id, validation_protocol_identity_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, validation_assessment_protocol_hash_hex) references investing.research_validation_assessment_protocols_scientific_identities (research_validation_assessment_protocol_identity_id, research_investigation_id, research_validation_protocol_identity_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_validation_assessment_result_fk foreign key (validation_assessment_result_identity_id, validation_assessment_protocol_identity_id, validation_result_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, validation_assessment_result_hash_hex) references investing.research_validation_assessment_results_scientific_identities (research_validation_assessment_result_identity_id, research_validation_assessment_protocol_identity_id, research_validation_result_identity_id, research_investigation_id, research_experiment_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_robustness_protocol_fk foreign key (robustness_comparison_protocol_identity_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, robustness_comparison_protocol_hash_hex) references investing.research_experiment_comparison_protocols_scientific_identities (research_experiment_comparison_protocol_identity_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_transitions_robustness_result_fk foreign key (robustness_comparison_result_identity_id, robustness_comparison_protocol_identity_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, robustness_comparison_result_hash_hex) references investing.research_experiment_comparison_results_scientific_identities (research_experiment_comparison_result_identity_id, research_experiment_comparison_protocol_identity_id, research_investigation_id, tenant_id, principal_id, tenant_membership_id, operation_scope, source_context, hash_hex),
  constraint research_scientific_promotion_predecessor_pair_check check ((predecessor_transition_identity_id is null and predecessor_transition_hash_hex is null) or (predecessor_transition_identity_id is not null and predecessor_transition_hash_hex is not null)),
  constraint research_scientific_promotion_rejected_pair_check check ((rejected_transition_identity_id is null and rejected_transition_hash_hex is null) or (rejected_transition_identity_id is not null and rejected_transition_hash_hex is not null)),
  constraint research_scientific_promotion_supersedes_pair_check check ((supersedes_transition_identity_id is null and supersedes_transition_hash_hex is null) or (supersedes_transition_identity_id is not null and supersedes_transition_hash_hex is not null)),
  constraint research_scientific_promotion_successor_protocol_pair_check check ((superseded_by_successor_protocol_identity_id is null and superseded_by_successor_protocol_hash_hex is null) or (superseded_by_successor_protocol_identity_id is not null and superseded_by_successor_protocol_hash_hex is not null)),
  constraint research_scientific_promotion_successor_root_pair_check check ((superseded_by_successor_root_transition_identity_id is null and superseded_by_successor_root_transition_hash_hex is null) or (superseded_by_successor_root_transition_identity_id is not null and superseded_by_successor_root_transition_hash_hex is not null)),
  constraint research_scientific_promotion_state_graph_check check ((predecessor_state = 'DRAFT_RESEARCH' and resulting_state = 'EXECUTED') or (predecessor_state in ('EXECUTED','INSUFFICIENT_EVIDENCE','PROMOTION_ELIGIBLE','REJECTED') and resulting_state in ('INSUFFICIENT_EVIDENCE','VALIDATION_FAILED','VALIDATION_PASSED')) or (predecessor_state = 'VALIDATION_FAILED' and resulting_state = 'REJECTED') or (predecessor_state = 'VALIDATION_PASSED' and resulting_state = 'PROMOTION_ELIGIBLE') or (predecessor_state in ('EXECUTED','INSUFFICIENT_EVIDENCE','PROMOTION_ELIGIBLE','REJECTED') and resulting_state = 'SUPERSEDED')),
  constraint research_scientific_promotion_lifecycle_presence_check check (((predecessor_state = 'DRAFT_RESEARCH' and resulting_state = 'EXECUTED' and predecessor_transition_identity_id is null and rejected_transition_identity_id is null and supersedes_transition_identity_id is null and superseded_by_successor_protocol_identity_id is null and superseded_by_successor_root_transition_identity_id is null) or (predecessor_transition_identity_id is not null and predecessor_state <> 'DRAFT_RESEARCH' and resulting_state <> 'EXECUTED'))),
  constraint research_scientific_promotion_rejected_presence_check check ((resulting_state = 'REJECTED' and rejected_transition_identity_id is not null) or (resulting_state <> 'REJECTED' and rejected_transition_identity_id is null)),
  constraint research_scientific_promotion_superseded_presence_check check ((resulting_state = 'SUPERSEDED' and supersedes_transition_identity_id is not null and superseded_by_successor_protocol_identity_id is not null and superseded_by_successor_root_transition_identity_id is not null and superseded_by_successor_protocol_hash_hex <> protocol_hash_hex) or (resulting_state <> 'SUPERSEDED' and supersedes_transition_identity_id is null and superseded_by_successor_protocol_identity_id is null and superseded_by_successor_root_transition_identity_id is null)),
  constraint research_scientific_promotion_payload_check check (jsonb_typeof(canonical_payload) = 'object' and not investing.rl8c_jsonb_has_number_v1(canonical_payload) and canonical_payload->>'schemaVersion' = 'SCIENTIFIC_PROMOTION_TRANSITION_V1' and canonical_payload->>'predecessorState' = predecessor_state and canonical_payload->>'resultingState' = resulting_state and canonical_payload#>>'{protocol,hashHex}' = protocol_hash_hex and canonical_payload#>>'{subject,subjectExperiment,hashHex}' = subject_experiment_hash_hex and canonical_payload#>>'{subject,subjectExperimentParameters,hashHex}' = subject_experiment_parameters_hash_hex and canonical_payload#>>'{subject,subjectResearchIr,hashHex}' = subject_research_ir_hash_hex and investing.rl8c_sha256_hex_v1(transition_hash_domain, canonical_payload) = transition_hash_hex),
  constraint research_scientific_promotion_transitions_rl8c_lifecycle_key unique (research_scientific_promotion_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, transition_hash_hex),
  constraint research_scientific_promotion_transitions_rl8c_cross_chain_target_key unique (research_scientific_promotion_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, protocol_hash_hex, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, transition_hash_hex),
  constraint research_scientific_promotion_transition_hash_key unique (transition_hash_algorithm, transition_hash_domain, transition_hash_version, transition_hash_hex)
);

alter table investing.research_scientific_promotion_transitions_scientific_identities add constraint research_scientific_promotion_predecessor_fk foreign key (predecessor_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, predecessor_transition_hash_hex) references investing.research_scientific_promotion_transitions_scientific_identities (research_scientific_promotion_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, transition_hash_hex) match simple;
alter table investing.research_scientific_promotion_transitions_scientific_identities add constraint research_scientific_promotion_rejected_fk foreign key (rejected_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, rejected_transition_hash_hex) references investing.research_scientific_promotion_transitions_scientific_identities (research_scientific_promotion_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, transition_hash_hex) match simple;
alter table investing.research_scientific_promotion_transitions_scientific_identities add constraint research_scientific_promotion_supersedes_fk foreign key (supersedes_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, supersedes_transition_hash_hex) references investing.research_scientific_promotion_transitions_scientific_identities (research_scientific_promotion_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, transition_hash_hex) match simple;
alter table investing.research_scientific_promotion_transitions_scientific_identities add constraint research_scientific_promotion_successor_protocol_fk foreign key (superseded_by_successor_protocol_identity_id, superseded_by_successor_protocol_hash_hex) references investing.research_scientific_promotion_protocols_scientific_identities (research_scientific_promotion_protocol_identity_id, hash_hex) match full;
alter table investing.research_scientific_promotion_transitions_scientific_identities add constraint research_scientific_promotion_successor_root_fk foreign key (superseded_by_successor_root_transition_identity_id, tenant_id, research_investigation_id, superseded_by_successor_protocol_identity_id, superseded_by_successor_protocol_hash_hex, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, superseded_by_successor_root_transition_hash_hex) references investing.research_scientific_promotion_transitions_scientific_identities (research_scientific_promotion_transition_identity_id, tenant_id, research_investigation_id, research_scientific_promotion_protocol_identity_id, protocol_hash_hex, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, transition_hash_hex) match simple;

create unique index research_scientific_promotion_one_root_per_chain_key on investing.research_scientific_promotion_transitions_scientific_identities (tenant_id, research_investigation_id, subject_experiment_hash_hex, subject_experiment_parameters_hash_hex, subject_research_ir_hash_hex, protocol_hash_hex) where predecessor_transition_identity_id is null;
create unique index research_scientific_promotion_one_successor_per_predecessor on investing.research_scientific_promotion_transitions_scientific_identities (tenant_id, research_investigation_id, predecessor_transition_identity_id) where predecessor_transition_identity_id is not null;

create trigger research_scientific_promotion_protocols_append_only before update or delete on investing.research_scientific_promotion_protocols_scientific_identities for each row execute function investing.reject_research_scientific_promotion_update_delete_v1();
create trigger research_scientific_promotion_transitions_append_only before update or delete on investing.research_scientific_promotion_transitions_scientific_identities for each row execute function investing.reject_research_scientific_promotion_update_delete_v1();

alter table investing.research_scientific_promotion_protocols_scientific_identities enable row level security;
alter table investing.research_scientific_promotion_protocols_scientific_identities force row level security;
alter table investing.research_scientific_promotion_transitions_scientific_identities enable row level security;
alter table investing.research_scientific_promotion_transitions_scientific_identities force row level security;

revoke all on investing.research_scientific_promotion_protocols_scientific_identities from public, anon, authenticated, service_role, investing_app;
revoke all on investing.research_scientific_promotion_transitions_scientific_identities from public, anon, authenticated, service_role, investing_app;
grant select on investing.research_scientific_promotion_protocols_scientific_identities to investing_app;
grant select on investing.research_scientific_promotion_transitions_scientific_identities to investing_app;

grant usage on schema investing to investing_rl8_writer;
grant usage on schema extensions to investing_rl8_writer;
grant select, insert on investing.research_scientific_promotion_protocols_scientific_identities to investing_rl8_writer;
grant select, insert on investing.research_scientific_promotion_transitions_scientific_identities to investing_rl8_writer;
grant select on investing.tenant_memberships to investing_rl8_writer;
grant select on investing.research_investigations to investing_rl8_writer;
grant select on investing.research_experiments to investing_rl8_writer;
grant select on investing.run_inputs_scientific_identities to investing_rl8_writer;
grant select on investing.research_results_scientific_identities to investing_rl8_writer;
grant select on investing.research_evidence_objects_scientific_identities to investing_rl8_writer;
grant select on investing.research_validation_protocols_scientific_identities to investing_rl8_writer;
grant select on investing.research_validation_results_scientific_identities to investing_rl8_writer;
grant select on investing.research_validation_assessment_protocols_scientific_identities to investing_rl8_writer;
grant select on investing.research_validation_assessment_results_scientific_identities to investing_rl8_writer;
grant select on investing.research_experiment_comparison_protocols_scientific_identities to investing_rl8_writer;
grant select on investing.research_experiment_comparison_results_scientific_identities to investing_rl8_writer;

create policy tenant_memberships_rl8c_writer_select on investing.tenant_memberships for select to investing_rl8_writer using (current_setting('syntrake.investing.operation', true) in ('RESEARCH_SCIENTIFIC_PROMOTION_PROTOCOL_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1') and current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and role = 'OWNER' and state = 'ACTIVE');
create policy research_investigations_rl8c_writer_select on investing.research_investigations for select to investing_rl8_writer using (current_setting('syntrake.investing.operation', true) in ('RESEARCH_SCIENTIFIC_PROMOTION_PROTOCOL_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1') and current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_experiments_rl8c_writer_select on investing.research_experiments for select to investing_rl8_writer using (current_setting('syntrake.investing.operation', true) in ('RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1') and current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy run_inputs_rl8c_writer_select on investing.run_inputs_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_results_rl8c_writer_select on investing.research_results_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_evidence_objects_rl8c_writer_select on investing.research_evidence_objects_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_validation_protocols_rl8c_writer_select on investing.research_validation_protocols_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_validation_results_rl8c_writer_select on investing.research_validation_results_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_validation_assessment_protocols_rl8c_writer_select on investing.research_validation_assessment_protocols_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_validation_assessment_results_rl8c_writer_select on investing.research_validation_assessment_results_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_experiment_comparison_protocols_rl8c_writer_select on investing.research_experiment_comparison_protocols_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_experiment_comparison_results_rl8c_writer_select on investing.research_experiment_comparison_results_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');

create policy research_scientific_promotion_protocols_rl8c_writer_select on investing.research_scientific_promotion_protocols_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.operation', true) in ('RESEARCH_SCIENTIFIC_PROMOTION_PROTOCOL_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1') and current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and exists (select 1 from investing.tenant_memberships tm where tm.tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and tm.tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and tm.principal_id::text = current_setting('syntrake.investing.principal_id', true) and tm.role = 'OWNER' and tm.state = 'ACTIVE') and exists (select 1 from investing.research_investigations ri where ri.research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and ri.tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and ri.principal_id::text = current_setting('syntrake.investing.principal_id', true) and ri.tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and ri.operation_scope = 'TENANT_SCOPE' and ri.source_context = 'PURE_RESEARCH'));
create policy research_scientific_promotion_protocols_rl8c_writer_insert on investing.research_scientific_promotion_protocols_scientific_identities for insert to investing_rl8_writer with check (operation = 'RESEARCH_SCIENTIFIC_PROMOTION_PROTOCOL_CREATE_V1' and capability = 'RESEARCH_MUTATE' and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH' and exists (select 1 from investing.tenant_memberships tm where tm.tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and tm.tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and tm.principal_id::text = current_setting('syntrake.investing.principal_id', true) and tm.role = 'OWNER' and tm.state = 'ACTIVE') and exists (select 1 from investing.research_investigations ri where ri.research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and ri.tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and ri.principal_id::text = current_setting('syntrake.investing.principal_id', true) and ri.tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and ri.operation_scope = 'TENANT_SCOPE' and ri.source_context = 'PURE_RESEARCH'));
create policy research_scientific_promotion_transitions_rl8c_writer_select on investing.research_scientific_promotion_transitions_scientific_identities for select to investing_rl8_writer using (current_setting('syntrake.investing.operation', true) in ('RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1') and current_setting('syntrake.investing.capability', true) = 'RESEARCH_MUTATE' and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH');
create policy research_scientific_promotion_transitions_rl8c_writer_insert on investing.research_scientific_promotion_transitions_scientific_identities for insert to investing_rl8_writer with check (current_setting('syntrake.investing.operation', true) in ('RESEARCH_SCIENTIFIC_PROMOTION_ROOT_CREATE_V1','RESEARCH_SCIENTIFIC_PROMOTION_EVALUATION_PLAN_PERSIST_V1','RESEARCH_SCIENTIFIC_PROMOTION_SUPERSESSION_PERSIST_V1') and operation = current_setting('syntrake.investing.operation', true) and capability = 'RESEARCH_MUTATE' and operation_scope = 'TENANT_SCOPE' and source_context = 'PURE_RESEARCH' and tenant_id::text = current_setting('syntrake.investing.tenant_id', true) and principal_id::text = current_setting('syntrake.investing.principal_id', true) and tenant_membership_id::text = current_setting('syntrake.investing.tenant_membership_id', true) and research_investigation_id::text = current_setting('syntrake.investing.research_investigation_id', true) and exists (select 1 from investing.tenant_memberships tm where tm.tenant_membership_id = research_scientific_promotion_transitions_scientific_identities.tenant_membership_id and tm.tenant_id = research_scientific_promotion_transitions_scientific_identities.tenant_id and tm.principal_id = research_scientific_promotion_transitions_scientific_identities.principal_id and tm.role = 'OWNER' and tm.state = 'ACTIVE') and exists (select 1 from investing.research_investigations ri where ri.research_investigation_id = research_scientific_promotion_transitions_scientific_identities.research_investigation_id and ri.tenant_id = research_scientific_promotion_transitions_scientific_identities.tenant_id and ri.principal_id = research_scientific_promotion_transitions_scientific_identities.principal_id and ri.tenant_membership_id = research_scientific_promotion_transitions_scientific_identities.tenant_membership_id and ri.operation_scope = 'TENANT_SCOPE' and ri.source_context = 'PURE_RESEARCH'));

do $$
declare v_writer_count integer;
begin
  if to_regclass('investing.research_scientific_promotion_protocols_scientific_identities') is null or to_regclass('investing.research_scientific_promotion_transitions_scientific_identities') is null then raise exception 'RL-8C1 postcondition failed: missing RL-8C1 tables'; end if;
  if exists (select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid = c.relnamespace where n.nspname = 'investing' and c.relname in ('research_scientific_promotion_protocols_scientific_identities','research_scientific_promotion_transitions_scientific_identities') and (pg_catalog.pg_get_userbyid(c.relowner) <> 'investing_owner' or not c.relrowsecurity or not c.relforcerowsecurity)) then raise exception 'RL-8C1 postcondition failed: table owner/RLS/FORCE RLS mismatch'; end if;
  if exists (select 1 from pg_catalog.pg_roles r where r.rolname = 'investing_rl8_writer' and (r.rolcanlogin or r.rolinherit or r.rolsuper or r.rolcreatedb or r.rolcreaterole or r.rolreplication or r.rolbypassrls)) then raise exception 'RL-8C1 postcondition failed: writer role attributes drift'; end if;
  if pg_catalog.pg_has_role('investing_app', 'investing_rl8_writer', 'member') or pg_catalog.pg_has_role('service_role', 'investing_rl8_writer', 'member') or pg_catalog.pg_has_role('investing_rl8_writer', 'investing_owner', 'member') then raise exception 'RL-8C1 postcondition failed: forbidden writer membership exists'; end if;
  if not exists (select 1 from pg_catalog.pg_policies where schemaname = 'investing' and policyname = 'tenant_memberships_rl8c_writer_select') then raise exception 'RL-8C1 postcondition failed: tenant_memberships policy missing'; end if;
  if exists (select 1 from information_schema.role_table_grants where table_schema = 'investing' and table_name in ('research_scientific_promotion_protocols_scientific_identities','research_scientific_promotion_transitions_scientific_identities') and grantee in ('PUBLIC','anon','authenticated','service_role','investing_app') and privilege_type in ('INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER')) then raise exception 'RL-8C1 postcondition failed: forbidden RL-8 table mutation grant exists'; end if;
  select count(*) into v_writer_count from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid = p.pronamespace where n.nspname = 'investing' and p.proname like 'persist_research_scientific_promotion%';
  if v_writer_count <> 0 then raise exception 'RL-8C1 postcondition failed: RL-8 writer SECURITY DEFINER surface must be zero in C1'; end if;
end $$;

reset role;
commit;
