import type { InvestingInstrument } from "@/lib/investing/types";

const CANONICAL_INVESTING_INSTRUMENTS: InvestingInstrument[] = [
  {
    symbol: "VWCE",
    name: "Vanguard FTSE All-World UCITS ETF",
    assetClass: "equity",
    market: "equities",
    role: "core_growth",
    domicile: "IE",
    currency: "USD",
    executionVenue: "Xetra / LSE",
    benchmarkEligible: true,
    liquidityTier: "high",
    taxTreatment: "ucits_accumulating",
    qualityStatus: "approved",
    suitabilityBucket: "core",
    qualityScore: 88,
    growthScore: 86,
    incomeScore: 24,
    inflationScore: 28,
    liquidityScore: 74,
    feeBps: 22,
    enabled: true,
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    assetClass: "equity",
    market: "equities",
    role: "core_growth",
    domicile: "US",
    currency: "USD",
    executionVenue: "NYSE Arca",
    benchmarkEligible: true,
    liquidityTier: "high",
    taxTreatment: "us_distributing",
    qualityStatus: "approved",
    suitabilityBucket: "core",
    qualityScore: 84,
    growthScore: 90,
    incomeScore: 28,
    inflationScore: 30,
    liquidityScore: 95,
    feeBps: 9,
    enabled: true,
  },
  {
    symbol: "AGGH",
    name: "iShares Core Global Aggregate Bond UCITS ETF",
    assetClass: "bond",
    market: "multi_asset",
    role: "income_ballast",
    domicile: "IE",
    currency: "EUR",
    executionVenue: "Xetra / LSE",
    benchmarkEligible: true,
    liquidityTier: "medium",
    taxTreatment: "bond_fund",
    qualityStatus: "approved",
    suitabilityBucket: "income",
    qualityScore: 82,
    growthScore: 24,
    incomeScore: 78,
    inflationScore: 20,
    liquidityScore: 68,
    feeBps: 10,
    enabled: true,
  },
  {
    symbol: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "commodity",
    market: "commodities",
    role: "inflation_hedge",
    domicile: "US",
    currency: "USD",
    executionVenue: "NYSE Arca",
    benchmarkEligible: false,
    liquidityTier: "high",
    taxTreatment: "commodity_grantor_trust",
    qualityStatus: "approved",
    suitabilityBucket: "hedge",
    qualityScore: 76,
    growthScore: 25,
    incomeScore: 0,
    inflationScore: 92,
    liquidityScore: 88,
    feeBps: 40,
    enabled: true,
  },
];

export function getCanonicalInvestingInstrumentMaster() {
  return CANONICAL_INVESTING_INSTRUMENTS.map((instrument) => ({ ...instrument }));
}

