import type {
  InvestingOrderStateSemanticsV1,
  InvestingOrderStateV1,
} from "@/lib/investing/engine/v1/phase3c/types";

export const INVESTING_ORDER_STATE_SEMANTICS_V1: Readonly<
  Record<InvestingOrderStateV1, InvestingOrderStateSemanticsV1>
> = {
  proposed: {
    state: "proposed",
    terminal: false,
    entersReserved: false,
    entersProjected: false,
    canonicalPendingStatus: null,
    cashEffect: "none",
    positionEffect: "none",
    partialFillRule: "fills_are_contradictory_before_approval",
    exceptionalRule: "proposal_is_not_an_economic_commitment",
    ambiguity: "none",
  },
  approved: {
    state: "approved",
    terminal: false,
    entersReserved: true,
    entersProjected: true,
    canonicalPendingStatus: "pending",
    cashEffect: "buy_debit_sell_credit_for_remainder",
    positionEffect: "buy_add_sell_subtract_for_remainder",
    partialFillRule: "only_unfilled_remainder_is_committed",
    exceptionalRule: "remains_committed_until_terminal_state",
    ambiguity: "none",
  },
  submitting: {
    state: "submitting",
    terminal: false,
    entersReserved: true,
    entersProjected: true,
    canonicalPendingStatus: "submitted",
    cashEffect: "buy_debit_sell_credit_for_remainder",
    positionEffect: "buy_add_sell_subtract_for_remainder",
    partialFillRule: "only_unfilled_remainder_is_committed",
    exceptionalRule: "submission_in_flight_remains_committed",
    ambiguity: "none",
  },
  submitted: {
    state: "submitted",
    terminal: false,
    entersReserved: true,
    entersProjected: true,
    canonicalPendingStatus: "submitted",
    cashEffect: "buy_debit_sell_credit_for_remainder",
    positionEffect: "buy_add_sell_subtract_for_remainder",
    partialFillRule: "only_unfilled_remainder_is_committed",
    exceptionalRule: "remains_committed_until_terminal_state",
    ambiguity: "none",
  },
  partially_filled: {
    state: "partially_filled",
    terminal: false,
    entersReserved: true,
    entersProjected: true,
    canonicalPendingStatus: "partially_filled",
    cashEffect: "buy_debit_sell_credit_for_remainder",
    positionEffect: "buy_add_sell_subtract_for_remainder",
    partialFillRule: "cumulative_unique_fills_are_subtracted_once",
    exceptionalRule: "zero_remainder_is_contradictory",
    ambiguity: "none",
  },
  reconciling: {
    state: "reconciling",
    terminal: false,
    entersReserved: true,
    entersProjected: true,
    canonicalPendingStatus: "reconciling",
    cashEffect: "buy_debit_sell_credit_for_remainder",
    positionEffect: "buy_add_sell_subtract_for_remainder",
    partialFillRule: "known_fills_are_subtracted_once_and_unknown_remainder_stays_committed",
    exceptionalRule: "state_is_retained_conservatively_and_quality_is_degraded",
    ambiguity: "degraded",
  },
  cancellation_requested: {
    state: "cancellation_requested",
    terminal: false,
    entersReserved: true,
    entersProjected: true,
    canonicalPendingStatus: "submitted",
    cashEffect: "buy_debit_sell_credit_for_remainder",
    positionEffect: "buy_add_sell_subtract_for_remainder",
    partialFillRule: "known_fills_are_subtracted_once",
    exceptionalRule: "reservation_is_released_only_after_cancel_confirmation",
    ambiguity: "none",
  },
  cancelled: {
    state: "cancelled",
    terminal: true,
    entersReserved: false,
    entersProjected: false,
    canonicalPendingStatus: null,
    cashEffect: "none",
    positionEffect: "none",
    partialFillRule: "already_filled_quantity_is_factual_and_never_replayed",
    exceptionalRule: "terminal_state_has_no_remainder",
    ambiguity: "none",
  },
  submission_failed: {
    state: "submission_failed",
    terminal: true,
    entersReserved: false,
    entersProjected: false,
    canonicalPendingStatus: null,
    cashEffect: "none",
    positionEffect: "none",
    partialFillRule: "fills_are_contradictory_for_failed_submission",
    exceptionalRule: "terminal_state_releases_reservation",
    ambiguity: "none",
  },
  rejected: {
    state: "rejected",
    terminal: true,
    entersReserved: false,
    entersProjected: false,
    canonicalPendingStatus: null,
    cashEffect: "none",
    positionEffect: "none",
    partialFillRule: "fills_are_contradictory_for_rejected_order",
    exceptionalRule: "terminal_state_releases_reservation",
    ambiguity: "none",
  },
  filled: {
    state: "filled",
    terminal: true,
    entersReserved: false,
    entersProjected: false,
    canonicalPendingStatus: null,
    cashEffect: "none",
    positionEffect: "none",
    partialFillRule: "filled_quantity_must_equal_order_quantity",
    exceptionalRule: "terminal_state_has_no_remainder",
    ambiguity: "none",
  },
  reconciled: {
    state: "reconciled",
    terminal: true,
    entersReserved: false,
    entersProjected: false,
    canonicalPendingStatus: null,
    cashEffect: "none",
    positionEffect: "none",
    partialFillRule: "accounting_state_is_already_factual_and_never_replayed",
    exceptionalRule: "terminal_state_has_no_remainder",
    ambiguity: "none",
  },
};

export function getInvestingOrderStateSemanticsV1(
  state: string,
): InvestingOrderStateSemanticsV1 | null {
  return Object.prototype.hasOwnProperty.call(INVESTING_ORDER_STATE_SEMANTICS_V1, state)
    ? INVESTING_ORDER_STATE_SEMANTICS_V1[state as InvestingOrderStateV1]
    : null;
}
